language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:mc3man/mpv-tests
  - sudo apt-get update
  - sudo apt-get -y install libgnutls28-dev
  - sudo apt-get -y install libmpv1
  - sudo apt-get -y install python3-tk
install:
  - pip install tox
script:
  - tox .
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - bash version.sh
