language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:mc3man/mpv-tests
  - sudo apt-get update
  - sudo apt-get -y install libgnutls28-dev
  - sudo apt-get -y install libmpv1
  - sudo apt-get -y install python3-tk
install:
  - pip install tox
script:
  - tox .
  - if [ -n "$TRAVIS_TAG" ]; then bash version.sh; fi
deploy:
  provider: releases    
  api_key: "$GITHUB_TOKEN"
  file: "ubuntu/kawaii-player-$TRAVIS_TAG.deb"
  skip_cleanup: true
  on:
    tags: true
